version: "3.8"

x-commons: &commons
  image: mongo:7.0.6
  volumes:
    - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  environment:
    MONGO_INITDB_ROOT_USERNAME: root
    MONGO_INITDB_ROOT_PASSWORD: password
    MONGO_INITDB_DATABASE: testdb
    TZ: Asia/Tokyo

services:
  mongo:
    container_name: go_batch_mongodb_aggregate_mongo
    <<: *commons
    ports:
      - "27017:27017"

  # mongo_ci:
  #   container_name: go_batch_mongodb_aggregate_mongo_ci
  #   <<: *commons
  #   ports:
  #     - "27018:27017"
